# Generated by Django 5.2.14 on 2026-06-02 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='项目名称')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='项目链接')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='Stars 数')),
                ('language', models.CharField(blank=True, default='', max_length=100, verbose_name='编程语言')),
                ('trending_date', models.DateField(default=django.utils.timezone.now, verbose_name='趋势日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': 'GitHub 热点',
                'verbose_name_plural': 'GitHub 热点',
                'ordering': ['-stars'],
            },
        ),
        migrations.CreateModel(
            name='NewsHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('url', models.URLField(max_length=500, verbose_name='原文链接')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('score', models.PositiveSmallIntegerField(verbose_name='AI 评分')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('publish_date', models.DateField(verbose_name='发布日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': '新闻热点',
                'verbose_name_plural': '新闻热点',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True, verbose_name='推文 ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('post_time', models.DateTimeField(verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': 'Twitter 动态',
                'verbose_name_plural': 'Twitter 动态',
                'ordering': ['-post_time'],
            },
        ),
    ]
