# Generated by Django 6.0 on 2026-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('url', models.URLField(max_length=500, verbose_name='原文链接')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('score', models.PositiveSmallIntegerField(verbose_name='AI 评分')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('publish_date', models.DateField(verbose_name='发布日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': 'Chrome 新闻',
                'verbose_name_plural': 'Chrome 新闻',
                'ordering': ['-score'],
            },
        ),
    ]
